model:
  name: mcla_stylegan2ada

  latent:
    space: w_plus
    num_layers: 18
    latent_dim: 512

  generator:
    name: stylegan2ada_wrapper
    repo_root: /root/autodl-tmp/Anchor-guided-Faithful-GAN-Inversion-for-Inpainting/anchorfill_gi/third_party/stylegan2-ada-pytorch
    checkpoint: /root/autodl-tmp/Anchor-guided-Faithful-GAN-Inversion-for-Inpainting/anchorfill_gi/pretrained/stylegan2/ffhq.pkl
    image_size: 1024
    noise_mode: const
    truncation_psi: 1.0
    freeze_generator: true

  mcla:
    in_channels: 4
    base_channels: 64
    max_channels: 512
    feat_dim: 512
    num_down: 4
    num_ws: 18
    w_dim: 512
    layer_splits: [4, 6, 8]
    delta_scale: 0.35
    gate_mode: channel
    use_edge_branch: true
    use_freq_branch: true