loss:
  latent_l1:
    enabled: true
    weight: 1.0

  latent_l2:
    enabled: true
    weight: 1.0

  image_known_l1:
    enabled: true
    weight: 1.0

  image_hole_l1:
    enabled: true
    weight: 1.0

  perceptual:
    enabled: false
    weight: 0.0
    net: alex