project:
  name: anchorfill_gi
  exp_name: default_exp
  seed: 42

paths:
  project_root: /root/autodl-tmp/Anchor-guided-Faithful-GAN-Inversion-for-Inpainting/anchorfill_gi
  data_root: /root/autodl-tmp/Anchor-guided-Faithful-GAN-Inversion-for-Inpainting/anchorfill_gi/data
  pretrained_root: /root/autodl-tmp/Anchor-guided-Faithful-GAN-Inversion-for-Inpainting/anchorfill_gi/pretrained
  output_root: /root/autodl-tmp/Anchor-guided-Faithful-GAN-Inversion-for-Inpainting/anchorfill_gi/outputs

system:
  device: cuda
  num_gpus: 1
  amp: true
  cudnn_benchmark: true

logging:
  log_interval: 10
  val_interval: 10
  save_interval: 10
  save_images: true
  image_save_num: 4

debug:
  enabled: true
  overfit_batch: true
  overfit_num_samples: 1
  fixed_mask: true